/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as CoordinatorLoginRouteImport } from './routes/coordinator/login'
import { Route as CoordinatorDashboardRouteImport } from './routes/coordinator/dashboard'
import { Route as PublicDonateRouteImport } from './routes/_public/donate'
import { Route as PublicCartRouteImport } from './routes/_public/cart'
import { Route as PublicBrowseRouteImport } from './routes/_public/browse'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicItemIdRouteImport } from './routes/_public/item.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const CoordinatorLoginRoute = CoordinatorLoginRouteImport.update({
  id: '/coordinator/login',
  path: '/coordinator/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorDashboardRoute = CoordinatorDashboardRouteImport.update({
  id: '/coordinator/dashboard',
  path: '/coordinator/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDonateRoute = PublicDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCartRoute = PublicCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBrowseRoute = PublicBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicItemIdRoute = PublicItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/browse': typeof PublicBrowseRoute
  '/cart': typeof PublicCartRoute
  '/donate': typeof PublicDonateRoute
  '/coordinator/dashboard': typeof CoordinatorDashboardRoute
  '/coordinator/login': typeof CoordinatorLoginRoute
  '/item/$id': typeof PublicItemIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/browse': typeof PublicBrowseRoute
  '/cart': typeof PublicCartRoute
  '/donate': typeof PublicDonateRoute
  '/coordinator/dashboard': typeof CoordinatorDashboardRoute
  '/coordinator/login': typeof CoordinatorLoginRoute
  '/': typeof PublicIndexRoute
  '/item/$id': typeof PublicItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/browse': typeof PublicBrowseRoute
  '/_public/cart': typeof PublicCartRoute
  '/_public/donate': typeof PublicDonateRoute
  '/coordinator/dashboard': typeof CoordinatorDashboardRoute
  '/coordinator/login': typeof CoordinatorLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/item/$id': typeof PublicItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/cart'
    | '/donate'
    | '/coordinator/dashboard'
    | '/coordinator/login'
    | '/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/browse'
    | '/cart'
    | '/donate'
    | '/coordinator/dashboard'
    | '/coordinator/login'
    | '/'
    | '/item/$id'
  id:
    | '__root__'
    | '/_public'
    | '/_public/about'
    | '/_public/browse'
    | '/_public/cart'
    | '/_public/donate'
    | '/coordinator/dashboard'
    | '/coordinator/login'
    | '/_public/'
    | '/_public/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  CoordinatorDashboardRoute: typeof CoordinatorDashboardRoute
  CoordinatorLoginRoute: typeof CoordinatorLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/coordinator/login': {
      id: '/coordinator/login'
      path: '/coordinator/login'
      fullPath: '/coordinator/login'
      preLoaderRoute: typeof CoordinatorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/dashboard': {
      id: '/coordinator/dashboard'
      path: '/coordinator/dashboard'
      fullPath: '/coordinator/dashboard'
      preLoaderRoute: typeof CoordinatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/donate': {
      id: '/_public/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof PublicDonateRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cart': {
      id: '/_public/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PublicCartRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/browse': {
      id: '/_public/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof PublicBrowseRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/item/$id': {
      id: '/_public/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof PublicItemIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicBrowseRoute: typeof PublicBrowseRoute
  PublicCartRoute: typeof PublicCartRoute
  PublicDonateRoute: typeof PublicDonateRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicItemIdRoute: typeof PublicItemIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicBrowseRoute: PublicBrowseRoute,
  PublicCartRoute: PublicCartRoute,
  PublicDonateRoute: PublicDonateRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicItemIdRoute: PublicItemIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  CoordinatorDashboardRoute: CoordinatorDashboardRoute,
  CoordinatorLoginRoute: CoordinatorLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
